before_script:
- "./scripts/travis_prebuild.sh"
language: clojure
script: "./go test"
cache:
  directories:
  - "$HOME/.m2"
env:
  matrix:
  - LAMBDACD_VERSION=0.13.5 CLOJURE_VERSION=1.7.0
  - LAMBDACD_VERSION=0.13.5 CLOJURE_VERSION=1.8.0
  - LAMBDACD_VERSION=0.13.4 CLOJURE_VERSION=1.7.0
  - LAMBDACD_VERSION=0.13.4 CLOJURE_VERSION=1.8.0
  - LAMBDACD_VERSION=0.13.3 CLOJURE_VERSION=1.7.0
  - LAMBDACD_VERSION=0.13.3 CLOJURE_VERSION=1.8.0
  global:
    secure: fAFV8k4idHNbnLa23Qz31kEONXHwT2EsDUuGwwY48DOMv8fkR1Bwlx8kyHv/IfFFhP+ODJYPwWYzv8waHUt0Nplk37p3ghPgrxoGWx61JMMIr8a4tlehanrBM3NvguiQ5pIn1PhmVUHm+7sykt/pHSd0i+2cbMaLHLECT3lLZafOaT6+8aLG3GuzN/NlOOiQFUh+zcqLDtxTZmC3CaCB4uVMX0MV2W3seUGUjQlVNy7Gyip4/RqNmAWY0pH1lDDbTEm7Xul+/Bf4R3oq6Qz/SKmB+5Mb5avA8UmD5DDrbqBbl8BBRPGS6lp71TJm7fQq9q8MGFR8nXaCzMrrCxBx9yF7tIGCipYOaCZusSVFWX0dLIt4oOlEyxka802hFs+6BboF601mgxijxE8wk2U9RkGW1zBLPFaF5gM3vAX9T/klQjqHx1AS4UJFHFE3xDaeYQCHeoRpfuyh2KdT8pyMEuL+LhxhC3/+6UaaqI+VwsTjUV2ZDjb9OEV4tPNsv1JioklOcdgw/1yhaHYT+C5CSOb1xRixkay2X9JjCkXuiU3OJRvA2h9y0GkLyFWwXxQuQq2I32vFznycl5ca9V77aZKF6WICcB2WRiXLP1C0u/4aMk7f0Mz7cDpQ+FWgbKmWSsFLf/G40Ol4Ivm9ELzeeDLOEOk2e9T43zyiS91QoFk=
